name: Build and Deploy on Server


on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy pull Node app from server
        uses: appleboy/ssh-action@v0.1.2
        
        
        with: 
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SERVER_PK}}
          username: ${{secrets.SERVER_USERNAME}}
          
          script: |
            killall -9 node
            cd /var/www/freelanzate/BackEnd
            git pull
            node app.js updateDatabase
            npx sequelize-cli db:seed:all
            node app.js
            cd /var/www/FrontEnd/src/
            npm run start
            echo 'pull finalizado'
